### ISSUE TITLE
Error - '.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by AlexSun98** [jody-zeitler/cuke-skywalker#8]
node ./node_modules/cuke-skywalker/bin/cuke-skywalker

Cucumber version: 4.2.1
Doling out 2 features across 4 workers as they are available.
1 features remaining
0 features remaining
'.' is not recognized as an internal or external command,
operable program or batch file.

Error: worker exited with code 1
    at ChildProcess.worker.on (C:\Bitbucket\Reckon.Stp.Jellyfish\node_modules\cuke-skywalker\index.js:162:12)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
'.' is not recognized as an internal or external command,
operable program or batch file.

Error: worker exited with code 1
    at ChildProcess.worker.on (C:\Bitbucket\Reckon.Stp.Jellyfish\node_modules\cuke-skywalker\index.js:162:12)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
2 workers had failures.

**Comment by jody-zeitler** [comment]
Workers are invoked using the shell, which is `cmd` on Windows, and it doesn't like POSIXy things like forward slashes or dots or shebangs. I don't think the shell is necessary at all but I'll need to check that I can remove it without affecting our pipelines. Disabling that will allow you to set the `CUCUMBER_JS_PATH` variable to the cmd file at `node_modules\\.bin\\cucumber-js.cmd`.

**Comment by AlexSun98** [comment]
thanks for your quick response. 👍
